server:
    port: 3000
    metrics:

s3:
    accessKeyId:
    secretAccessKey:
    region:
    bucket:

firehose:
    accessKeyId:
    secretAccessKey:
    region:
    stream:

gcp:
    bucket:
    dataset:
    table:
    fields:

    maxFlushTime:
    bufferSize:

github:
    client_id: GITHUB_CLIENT_ID
    client_secret: GITHUB_SECRET
    callback_url: GITHUB_CALLBACK_URL
